# Generated by Django 5.0.2 on 2024-06-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tempotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='user name'),
        ),
    ]
